### ISSUE TITLE
Instruction about how to flash this code

### ISSUE THREAD

**Issue by iamfaith** [uvwxy/arduino-beacon#1]
Thanks for your amazing repo.

But could you please give me some instructions about how to use this code? I am a beginner in ESP32. really thanks a lot.

**Comment by uvwxy** [comment]
Get Visual Studio Code and install the PlatformIO add-on, then open this repository with VSC.

**Comment by iamfaith** [comment]
Thanks for your tips. I can flash this code! May I ask how could I improve the accuracy? The distance shown in the locate APP is not accurate.

**Comment by uvwxy** [comment]
Check the value for `    adv_data[29] = 0xD8; // Beacons TX power` in `SimpleBeacon.cpp`.

I don't now myself what value to put there... maybe this helps?

**Comment by uvwxy** [comment]
@iamfaith  can we close this? :)

**Comment by iamfaith** [comment]
Thanks, I will close it.
